// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VebTech.Data.Contexts;

#nullable disable

namespace VebTech.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231011213740_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VebTech.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d2a8348-203d-4135-ba65-491e134eaf68"),
                            RoleName = "User"
                        },
                        new
                        {
                            Id = new Guid("a639ddb4-02e8-4e48-a261-e1e46b525a95"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("670dbe30-9559-4769-9d7a-9586a6792c43"),
                            RoleName = "Support"
                        },
                        new
                        {
                            Id = new Guid("a50b5ab1-dcb9-4afa-a18a-d5c2beae174e"),
                            RoleName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("VebTech.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef1a0d40-2d0e-488e-aa8d-b822d1a4296a"),
                            Age = 18,
                            Email = "user@gmail.com",
                            Name = "User",
                            PasswordHash = "$2a$11$rhe4VNKFX8Glsz/5E36rHeisum8bBa7XdBb8Bc/X4Ufc5Kw2uXDie"
                        },
                        new
                        {
                            Id = new Guid("e97dfc7d-e0e1-4d4b-9d16-14c0bdaccd66"),
                            Age = 18,
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$JnL5poycc3YNwklfoilHLuSW2LBWDIdX4KyRchIzqwQi6NxyUE7/i"
                        },
                        new
                        {
                            Id = new Guid("cf4fa1ad-f8fc-4aaa-a9e7-b82baf8f7fb7"),
                            Age = 18,
                            Email = "SuperAdminAndAdmin@gmail.com",
                            Name = "SupportAndAdmin",
                            PasswordHash = "$2a$11$VJt9haQildwr6fGQshWPa.0HQlmjK1r7iGe0DXS6mutCJ3j2bbjOC"
                        },
                        new
                        {
                            Id = new Guid("d30159c4-d99e-4ee0-ae00-686c3db430e4"),
                            Age = 18,
                            Email = "SuperAdmin@gmail.com",
                            Name = "SuperAdmin",
                            PasswordHash = "$2a$11$oVL9A6rynLrXQ5zJ9v6dz.dnhcGdvJmCSNH2XSJTe.Fp/HNXLlW1."
                        });
                });

            modelBuilder.Entity("VebTech.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ef1a0d40-2d0e-488e-aa8d-b822d1a4296a"),
                            RoleId = new Guid("1d2a8348-203d-4135-ba65-491e134eaf68")
                        },
                        new
                        {
                            UserId = new Guid("e97dfc7d-e0e1-4d4b-9d16-14c0bdaccd66"),
                            RoleId = new Guid("a639ddb4-02e8-4e48-a261-e1e46b525a95")
                        },
                        new
                        {
                            UserId = new Guid("cf4fa1ad-f8fc-4aaa-a9e7-b82baf8f7fb7"),
                            RoleId = new Guid("670dbe30-9559-4769-9d7a-9586a6792c43")
                        },
                        new
                        {
                            UserId = new Guid("cf4fa1ad-f8fc-4aaa-a9e7-b82baf8f7fb7"),
                            RoleId = new Guid("a639ddb4-02e8-4e48-a261-e1e46b525a95")
                        },
                        new
                        {
                            UserId = new Guid("d30159c4-d99e-4ee0-ae00-686c3db430e4"),
                            RoleId = new Guid("a50b5ab1-dcb9-4afa-a18a-d5c2beae174e")
                        });
                });

            modelBuilder.Entity("VebTech.Data.Entities.UserRole", b =>
                {
                    b.HasOne("VebTech.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VebTech.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VebTech.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VebTech.Data.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
